import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Providers } from "../providers"; 
import NavbarUser from "@/components/ui/navbar";
import { Toaster } from "@/components/ui/toaster";
import Footer from "@/components/ui/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({

  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers> 
        <NavbarUser/>
        <Toaster />
          {children}
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}
